In [2]:
import pandas as pd
df = pd.read_excel("E:\\mp\\new adidas.xlsx")
df.head()

,Retailer,Retailer ID,InvoiceDate,Region,State,City,Product,Price per Unit,UnitsSold,TotalSales,OperatingProfit,OperatingMargin,SalesMethod
0,Foot Locker,1185732,2020-01-01,Northeast,New York,New York,Men's Street Footwear,50.0,1200,600000.0,300000.0,0.50,In-store
1,Foot Locker,1185732,2020-01-02,Northeast,New York,New York,Men's Athletic Footwear,50.0,1000,500000.0,150000.0,0.30,In-store
2,Foot Locker,1185732,2020-01-03,Northeast,New York,New York,Women's Street Footwear,40.0,1000,400000.0,140000.0,0.35,In-store
3,Foot Locker,1185732,2020-01-04,Northeast,New York,New York,Women's Athletic Footwear,45.0,850,382500.0,133875.0,0.35,In-store
4,Foot Locker,1185732,2020-01-05,Northeast,New York,New York,Men's Apparel,60.0,900,540000.0,162000.0,0.30,In-store

In [3]:
states_abbreviation = { "Alabama": "AL", "Alaska": "AK", "Arizona": "AZ", "Arkansas": "AR", "California": "CA", "Colorado": "CO", "Connecticut": "CT", "Delaware": "DE", "Florida": "FL", "Georgia": "GA", "Hawaii": "HI", "Idaho": "ID", "Illinois": "IL", "Indiana": "IN", "Iowa": "IA", "Kansas": "KS", "Kentucky": "KY", "Louisiana": "LA", "Maine": "ME", "Maryland": "MD", "Massachusetts": "MA", "Michigan": "MI", "Minnesota": "MN", "Mississippi": "MS", "Missouri": "MO", "Montana": "MT", "Nebraska": "NE", "Nevada": "NV", "New Hampshire": "NH", "New Jersey": "NJ", "New Mexico": "NM", "New York": "NY", "North Carolina": "NC", "North Dakota": "ND", "Ohio": "OH", "Oklahoma": "OK", "Oregon": "OR", "Pennsylvania": "PA", "Rhode Island": "RI", "South Carolina": "SC", "South Dakota": "SD", "Tennessee": "TN", "Texas": "TX", "Utah": "UT", "Vermont": "VT", "Virginia": "VA", "Washington": "WA", "West Virginia": "WV", "Wisconsin": "WI", "Wyoming": "WY", "District of Columbia": "DC", "American Samoa": "AS", "Guam": "GU", "Northern Mariana Islands": "MP", "Puerto Rico": "PR", "United States Minor Outlying Islands": "UM", "U.S. Virgin Islands": "VI" }

In [4]:
df['state_code'] = df['State'].map(states_abbreviation)

In [5]:
df.head()

,Retailer,Retailer ID,InvoiceDate,Region,State,City,Product,Price per Unit,UnitsSold,TotalSales,OperatingProfit,OperatingMargin,SalesMethod,state_code
0,Foot Locker,1185732,2020-01-01,Northeast,New York,New York,Men's Street Footwear,50.0,1200,600000.0,300000.0,0.50,In-store,NY
1,Foot Locker,1185732,2020-01-02,Northeast,New York,New York,Men's Athletic Footwear,50.0,1000,500000.0,150000.0,0.30,In-store,NY
2,Foot Locker,1185732,2020-01-03,Northeast,New York,New York,Women's Street Footwear,40.0,1000,400000.0,140000.0,0.35,In-store,NY
3,Foot Locker,1185732,2020-01-04,Northeast,New York,New York,Women's Athletic Footwear,45.0,850,382500.0,133875.0,0.35,In-store,NY
4,Foot Locker,1185732,2020-01-05,Northeast,New York,New York,Men's Apparel,60.0,900,540000.0,162000.0,0.30,In-store,NY

In [6]:
df.to_csv("Adidas_with_state_code.csv", index=False)

In [7]:
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])
df['Year'] = df['InvoiceDate'].dt.year

In [8]:
total_sales_by_state = df.groupby(['Year','State','state_code'])['TotalSales'].sum().reset_index()

In [9]:
print(total_sales_by_state)

    Year           State state_code  TotalSales
0   2020      California         CA   8709390.0
1   2020        Colorado         CO  20996536.0
2   2020         Florida         FL  31600863.0
3   2020       Minnesota         MN   7378068.0
4   2020          Nevada         NV  20858509.0
5   2020        New York         NY  39801235.0
6   2020    Pennsylvania         PA    948474.0
7   2020           Texas         TX  25456882.0
8   2020      Washington         WA  26330718.0
9   2021         Alabama         AL  17633424.0
10  2021          Alaska         AK  14753103.0
11  2021         Arizona         AZ  15782221.0
12  2021        Arkansas         AR  12639347.0
13  2021      California         CA  51464743.0
14  2021     Connecticut         CT  11573448.0
15  2021        Delaware         DE  12298412.0
16  2021         Florida         FL  27682851.0
17  2021         Georgia         GA  18997466.0
18  2021          Hawaii         HI  22282457.0
19  2021           Idaho         ID  19276878.0
20  2021        Illinois         IL   9797488.0
21  2021         Indiana         IN   8836198.0
22  2021            Iowa         IA   7424011.0
23  2021          Kansas         KS   9972864.0
24  2021        Kentucky         KY  10072848.0
25  2021       Louisiana         LA  23750781.0
26  2021           Maine         ME   9195978.0
27  2021        Maryland         MD   7758059.0
28  2021   Massachusetts         MA  11076810.0
29  2021        Michigan         MI  18625433.0
30  2021     Mississippi         MS  15591709.0
31  2021        Missouri         MO   9683265.0
32  2021         Montana         MT  15710886.0
33  2021        Nebraska         NE   5929038.0
34  2021   New Hampshire         NH  16411667.0
35  2021      New Jersey         NJ   9934246.0
36  2021      New Mexico         NM  19865016.0
37  2021        New York         NY  24427804.0
38  2021  North Carolina         NC  23956531.0
39  2021    North Dakota         ND   7735580.0
40  2021            Ohio         OH  18484583.0
41  2021        Oklahoma         OK  10620734.0
42  2021          Oregon         OR  21349674.0
43  2021    Pennsylvania         PA   9409045.0
44  2021    Rhode Island         RI   8446806.0
45  2021  South Carolina         SC  29285637.0
46  2021    South Dakota         SD   8495576.0
47  2021       Tennessee         TN  18067440.0
48  2021           Texas         TX  20902864.0
49  2021            Utah         UT   9696420.0
50  2021         Vermont         VT  14352923.0
51  2021        Virginia         VA  21575040.0
52  2021   West Virginia         WV  10689160.0
53  2021       Wisconsin         WI   7727469.0
54  2021         Wyoming         WY  18577517.0

In [10]:
total_sales_by_state.to_csv("total_sales_by_state.csv", index=False)

In [11]:
df2 = pd.read_csv("E:\\mp\\Adidas_with_state_code.csv")

In [19]:
total_sales_by_state_retailer = df2.groupby(['State','Retailer','state_code'])['TotalSales'].sum().reset_index()

In [20]:
total_sales_by_state_retailer.head()

     State       Retailer state_code  TotalSales
0  Alabama         Amazon         AL    409091.0
1  Alabama  Sports Direct         AL  17224333.0
2   Alaska         Amazon         AK  13365025.0
3   Alaska    Foot Locker         AK   1388078.0
4  Arizona    Foot Locker         AZ  13155216.0

In [22]:
total_sales_by_state_retailer.to_csv("total_sales_of_Retailers_by_state.csv", index=False)

In [23]:
df3 = pd.read_csv("E:\\mp\\Adidas_with_state_code.csv")

In [29]:
Sales_by_Product= df2.groupby(['State','Product','state_code'])['UnitsSold'].sum().reset_index()

In [30]:
Sales_by_Product.head()

     State                    Product state_code  UnitsSold
0  Alabama              Men's Apparel         AL       7285
1  Alabama    Men's Athletic Footwear         AL      12232
2  Alabama      Men's Street Footwear         AL      12612
3  Alabama            Women's Apparel         AL      11828
4  Alabama  Women's Athletic Footwear         AL       8003

In [31]:
Sales_by_Product.to_csv("Sales_by_Product.csv", index=False)

In [32]:
df4 = pd.read_csv("E:\\mp\\Adidas_with_state_code.csv")

In [33]:
Salesmethod_by_state= df2.groupby(['State','SalesMethod','state_code'])['TotalSales'].sum().reset_index()

In [34]:
Salesmethod_by_state.head()

     State SalesMethod state_code  TotalSales
0  Alabama      Online         AL    441556.0
1  Alabama      Outlet         AL  17191868.0
2   Alaska      Online         AK    372353.0
3   Alaska      Outlet         AK  14380750.0
4  Arizona      Online         AZ  15425512.0

In [35]:
Salesmethod_by_state.to_csv("Salesmethod_by_state.csv", index=False)