In [1]:
import pandas as pd
df = pd.read_excel("C:\\gayathri\\new adidas.xlsx")
df.head()

,Retailer,InvoiceDate,Region,State,City,Product,Price per Unit,UnitsSold,TotalSales,OperatingProfit,OperatingMargin,SalesMethod
0,kohl's,2019-01-01,South,Arkansas,Little Rock,Men's Street Footwear,55.0,1399,76945.0,45400.0,59.0,In-store
1,sports direct,2019-01-01,Midwest,Ohio,Columbus,Men's Street Footwear,50.0,1965,98250.0,46180.0,47.0,Outlet
2,amazon,2019-01-01,Northeast,Delaware,Wilmington,Women's Athletic Footwear,60.0,1312,78720.0,40150.0,51.0,Online
3,amazon,2019-01-01,West,Arizona,Phoenix,Women's Apparel,65.0,1967,127855.0,71600.0,56.0,Online
4,walmart,2019-01-01,West,Nevada,Las Vegas,Men's Street Footwear,40.0,1149,45960.0,17010.0,37.0,Online

In [2]:
states_abbreviation = { "Alabama": "AL", "Alaska": "AK", "Arizona": "AZ", "Arkansas": "AR", "California": "CA", "Colorado": "CO", "Connecticut": "CT", "Delaware": "DE", "Florida": "FL", "Georgia": "GA", "Hawaii": "HI", "Idaho": "ID", "Illinois": "IL", "Indiana": "IN", "Iowa": "IA", "Kansas": "KS", "Kentucky": "KY", "Louisiana": "LA", "Maine": "ME", "Maryland": "MD", "Massachusetts": "MA", "Michigan": "MI", "Minnesota": "MN", "Mississippi": "MS", "Missouri": "MO", "Montana": "MT", "Nebraska": "NE", "Nevada": "NV", "New Hampshire": "NH", "New Jersey": "NJ", "New Mexico": "NM", "New York": "NY", "North Carolina": "NC", "North Dakota": "ND", "Ohio": "OH", "Oklahoma": "OK", "Oregon": "OR", "Pennsylvania": "PA", "Rhode Island": "RI", "South Carolina": "SC", "South Dakota": "SD", "Tennessee": "TN", "Texas": "TX", "Utah": "UT", "Vermont": "VT", "Virginia": "VA", "Washington": "WA", "West Virginia": "WV", "Wisconsin": "WI", "Wyoming": "WY", "District of Columbia": "DC", "American Samoa": "AS", "Guam": "GU", "Northern Mariana Islands": "MP", "Puerto Rico": "PR", "United States Minor Outlying Islands": "UM", "U.S. Virgin Islands": "VI" }

In [3]:
df['state_code'] = df['State'].map(states_abbreviation)

In [4]:
df.head()

,Retailer,InvoiceDate,Region,State,City,Product,Price per Unit,UnitsSold,TotalSales,OperatingProfit,OperatingMargin,SalesMethod,state_code
0,kohl's,2019-01-01,South,Arkansas,Little Rock,Men's Street Footwear,55.0,1399,76945.0,45400.0,59.0,In-store,AR
1,sports direct,2019-01-01,Midwest,Ohio,Columbus,Men's Street Footwear,50.0,1965,98250.0,46180.0,47.0,Outlet,OH
2,amazon,2019-01-01,Northeast,Delaware,Wilmington,Women's Athletic Footwear,60.0,1312,78720.0,40150.0,51.0,Online,DE
3,amazon,2019-01-01,West,Arizona,Phoenix,Women's Apparel,65.0,1967,127855.0,71600.0,56.0,Online,AZ
4,walmart,2019-01-01,West,Nevada,Las Vegas,Men's Street Footwear,40.0,1149,45960.0,17010.0,37.0,Online,NV

In [5]:
df.to_csv("Adidas_with_state_code.csv", index=False)

In [6]:
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])
df['Year'] = df['InvoiceDate'].dt.year

In [7]:
total_sales_by_state = df.groupby(['Year','State','state_code'])['TotalSales'].sum().reset_index()

In [8]:
print(total_sales_by_state)

     Year          State state_code  TotalSales
0    2019        Alabama         AL  18253165.0
1    2019         Alaska         AK  10629115.0
2    2019        Arizona         AZ  11381640.0
3    2019       Arkansas         AR  17811595.0
4    2019     California         CA  11839610.0
..    ...            ...        ...         ...
100  2021        Vermont         VT  14352923.0
101  2021       Virginia         VA  21575040.0
102  2021  West Virginia         WV  10689160.0
103  2021      Wisconsin         WI   7727469.0
104  2021        Wyoming         WY  18577517.0

[105 rows x 4 columns]

In [9]:
total_sales_by_state.to_csv("total_sales_by_state.csv", index=False)

In [10]:
df2 = pd.read_csv("C:\\gayathri\\Adidas_with_state_code.csv")

In [11]:
total_sales_by_state_retailer = df2.groupby(['State','Retailer','state_code'])['TotalSales'].sum().reset_index()

In [12]:
total_sales_by_state_retailer.head()

     State       Retailer state_code  TotalSales
0  Alabama         amazon         AL   3555826.0
1  Alabama    foot locker         AL   2509950.0
2  Alabama         kohl's         AL   3180585.0
3  Alabama  sports direct         AL  19616508.0
4  Alabama        walmart         AL   3217890.0

In [13]:
total_sales_by_state_retailer.to_csv("total_sales_of_Retailers_by_state.csv", index=False)

In [14]:
df3 = pd.read_csv("C:\\gayathri\\Adidas_with_state_code.csv")

In [15]:
Sales_by_Product= df2.groupby(['State','Product','state_code'])['UnitsSold'].sum().reset_index()

In [16]:
Sales_by_Product.head()

     State                    Product state_code  UnitsSold
0  Alabama              Men's Apparel         AL      87995
1  Alabama    Men's Athletic Footwear         AL      64614
2  Alabama      Men's Street Footwear         AL      82829
3  Alabama            Women's Apparel         AL      74203
4  Alabama  Women's Athletic Footwear         AL      64130

In [17]:
Sales_by_Product.to_csv("Sales_by_Product.csv", index=False)

In [18]:
df4 = pd.read_csv("C:\\gayathri\\Adidas_with_state_code.csv")

In [19]:
Salesmethod_by_state= df2.groupby(['State','SalesMethod','state_code'])['TotalSales'].sum().reset_index()

In [20]:
Salesmethod_by_state.head()

     State SalesMethod state_code  TotalSales
0  Alabama    In-store         AL   5281760.0
1  Alabama      Online         AL   8850111.0
2  Alabama      Outlet         AL  21754718.0
3   Alaska    In-store         AK   2566965.0
4   Alaska      Online         AK   4744818.0

In [21]:
Salesmethod_by_state.to_csv("Salesmethod_by_state.csv", index=False)